language: node_js
script: echo "do nothing"
deploy:
  provider: s3
  access_key_id:
    secure: "JZiYfZmbcnC+OinsZ6nVC1rVR1zAOrKDWjjPHILmP2gpuVa3J3VVGQ7hO1t5igbOwKSc95NLPbDxUB4rEaCO1tUeZTK8Zl1tczlm37UkU5hDbS6vn6pAtBAtBzoJ6Ymt3xQkSsvscAVNydrpAwZ693supqUZaBd0OzAgHaxCzsWWPlFBGnlYuANZKzGQFzhRmOPhgHOEoJJajRBZ4ONDMVriuZ0KUvlyu6A3u0cdlxlV2LTJgw97bDZt7xbrFMV+nVnWzNAeB4k4tf5TGU+af5Wc0XXL2Lb0ROJ+9jd0/HovTB4DuTM47yFC886HEutzAkB69zhVcKB2nrlJbqu6iHs0CXPzHdY/v/noWh8UZmWjLOUnAR4BUlsl0pkg5JID9YkktBdgb2svU3YhEswtWvmRmTU+c5ndLR3+kCsW1ztXhGL15wmCTsyszzc+beTc1upgfm4Qehwlb0qLbvGWFt1EqAVy83GvaUiSIQ9ll83Po1RL4BeNavx9G2sNYJxALcKMI16esFsE0awY0pyQiqlaWYT8HaEQQ9Y/xRN9+Vl5v60NQC79ZCebfGR9BFTK+ToCMPa+wHlShSUC6+hZYcWt+nOq/IigVtJhdqfyvw0d9djsLhY6Qzi4+yFE7+BJPc+6dvTXfszTlKCb7L8gczGJGkDtDfZfzkzMPez2hho="
  secret_access_key:
    secure: "imymjVIKDtCudP+mj3oQ3NP5iiwB8SmzIA2SKLEmfP7JO8rELd3HUfb0jzYZEO/Lg50Ffah19/plDY981QPvLW5JyFPSSUY7VkUU8xxhX9tW9dEIFCLib/NuLrBxjJ70XmvBksftKiDfieVLXIYE3gkbVTWP3dc8Z+6uMbOZd9hDBWlRjNWvO1/keL7rV4uCgMKP0rpZ268iU2dtxmFAtJy+tnhKG0BDb1Tke+vezOAwtt6RsYYOmtmOzbzxseb1SFT7Ai7xB4arQ8MQdnnXkhSo3WB1gGjVhMBXNfnJQ/sBwWLVE8Xk1K6SgUnFXilIxSMAi2Fyh816wdZcFmNX1m0eCKEgkrcjmUKKbHrRssn0q+vNZ/xa7Dmhfz9N5Jgy1HqGOznMHYMc3QcadLmcpZZoQDQUAexobGkGW66PvhCFfrMFQNOYvbMC19H5pN1PpRx0lI8mSIk1VQ4J/vYYMbUzxWZegfMSddjFQA2GwlfH4WaJujx8zh+MI6L7q8aFCsAQ2Ir2X1SVFZIxbIa3cTHBCrSmYMhsA6uael5pHklspWwj7lP+WChIHaiM+5TY2VeHGUs19saZbqQ3GIZikmGC8ohG1JeoKkffzgnaq7hchUfZV8RWP706zhBeSQDFW1xRSqqIoPH0KqP9eWOK2SQJKK0pnkb7zv3rOND15lg="
  bucket: editor-ugwis-net
  region: us-east-1
  endpoint: s3.amazonaws.com
  on:
    branch: master
