language: python
python:
  - "3.5"
cache: pip
install:
  - pip install awscli
script:
  - echo "Do nothing"
deploy:
  provider: script
  script: aws s3 sync dist s3://editor-ugwis-net --region=ap-northeast-1 --delete
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id "ELHV96H5YN66D" --paths "/*"
