name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Upload S3
      uses: peter-evans/s3-backup@v1.0.0
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        MIRROR_TARGET: www-opencompiler-net/
      with:
        args: --overwrite --remove
    - name: CloudFront(E288A1TVL2TI12) Cache Invalidation
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: E288A1TVL2TI12
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: CloudFront(E1LBJUJYJ4Y70N) Cache Invalidation
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: E1LBJUJYJ4Y70N
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
