name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: GitHub # default: 8398a7@action-slack
        channel: ${{ secrets.SLACK_CHANNEL }}
        icon_emoji: ':github:'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
    - name: S3 Upload
      uses: jakejarvis/s3-sync-action@master
      env:
        AWS_S3_BUCKET: 'www-opencompiler-net'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-1'   # optional: defaults to us-east-1
    - name: CloudFront(E288A1TVL2TI12) Cache Invalidation
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: E288A1TVL2TI12
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: CloudFront(E1LBJUJYJ4Y70N) Cache Invalidation
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: E1LBJUJYJ4Y70N
        PATHS: '/*'
        AWS_REGION: 'us-east-1'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
